# Generated by Django 2.1.7 on 2019-03-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydb',
            options={'verbose_name': 'CountryDB', 'verbose_name_plural': 'CountryDB'},
        ),
    ]
