# Generated by Django 2.1.7 on 2019-03-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmschedule', '0004_countryfarmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=120)),
                ('village', models.CharField(max_length=120)),
                ('crop', models.CharField(max_length=50)),
                ('sowing_date', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmschedule.CountryFarmer')),
            ],
            options={
                'verbose_name': 'Farm',
            },
        ),
    ]
