# Generated by Django 2.1.7 on 2019-03-12 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmschedule', '0005_countryfarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SowingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField()),
                ('fertilizer', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmschedule.CountryFarm')),
            ],
        ),
    ]
