# Generated by Django 2.1.7 on 2019-03-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmschedule', '0006_sowingschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sowingschedule',
            name='fertilizer',
        ),
        migrations.RemoveField(
            model_name='sowingschedule',
            name='unit',
        ),
        migrations.AddField(
            model_name='sowingschedule',
            name='fert_type',
            field=models.CharField(choices=[('solid', 'SOLID'), ('liquid', 'LIQUID')], default='solid', max_length=10),
        ),
        migrations.AddField(
            model_name='sowingschedule',
            name='fert_unit',
            field=models.CharField(choices=[('ton', 'TON'), ('kg', 'KG'), ('gram', 'gram'), ('l', 'L'), ('ml', 'ML')], default='kg', max_length=5),
        ),
    ]
