# Generated by Django 2.1.7 on 2019-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmschedule', '0007_auto_20190312_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowingschedule',
            name='fert_unit',
            field=models.CharField(choices=[('1000', 'ton'), ('1', 'kg'), ('.001', 'gram'), ('l', 'L'), ('ml', 'ML')], default='1', max_length=5),
        ),
    ]
