# Generated by Django 2.1.7 on 2019-03-12 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmschedule', '0008_auto_20190312_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfarmer',
            name='phone',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(regex='/^(\\+\\d{1,3}[- ]?)?\\d{10}$/')]),
        ),
        migrations.AlterField(
            model_name='sowingschedule',
            name='fert_unit',
            field=models.CharField(choices=[('1000', 'ton'), ('1', 'kg'), ('.001', 'gram'), ('1000', 'l'), ('.001', 'ml')], default='1', max_length=5),
        ),
    ]
